# SPDX-FileCopyrightText: Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

# carbide-rest-workflow configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: carbide-rest-workflow-config
  labels:
    app: carbide-rest-workflow
data:
  config.yaml: |
    env:
      dev: true

    log:
      level: debug

    db:
      host: postgres
      port: 5432
      name: forge
      user: forge
      password: forge

    temporal:
      host: temporal-frontend.temporal
      port: 7233
      serverName: server.temporal.nvidia.com
      namespace: cloud
      queue: cloud
      tls:
        enabled: true
        certPath: /var/secrets/temporal/certs/tls.crt
        keyPath: /var/secrets/temporal/certs/tls.key
        caPath: /var/secrets/temporal/certs/ca.crt
        disableHostVerification: false
      encryptionKeyPath: /var/secrets/temporal/encryption-key

    ngc:
      api:
        baseUrl: https://api.stg.ngc.nvidia.com

    notifications:
      slack:
        webhookURL: ""

    metrics:
      enabled: true
      port: 9360

    tracing:
      enabled: false
      serviceName: cloud-workflow

